### ISSUE TITLE
FaceBook how to get user email?

### ISSUE THREAD

**Issue by vladarta** [Nodge/yii-eauth#107]
Added to config
'facebook' => array(
                    'scope' => 'email'
                ),
в массиве сервиса вроде бы появился scope
 ["scopes":protected]=> array(1) { [0]=> string(5) "email"
но
$eauth->getAttributes()
не содержит email
Делал проверку своего аккаунта на демо приложении eauth - там массив полный - email есть.

**Comment by Nodge** [comment]
Начиная с GraphAPI v2.4 нужно явно указывать набор желаемых полей в запросе.
Обновил пример: https://github.com/Nodge/yii-eauth/blob/master/custom_services/CustomFacebookService.php

**Comment by annechko** [comment]
запрос выглядит так
 $this->attributes = $this->makeSignedRequest('me', [
            'query' => [
                'fields' => join(',', [
                    'id',
                    'name',
                    'link',
                    'email',
                    'verified',
                    'first_name',
                    'last_name',
                    'gender',
                    'birthday',
                    'hometown',
                    'location',
                    'locale',
                    'timezone',
                    'updated_time',
                ])
            ]

но в $this->getAttributes() пишет только такое

'id' =>
  'name' 
  'link' 
  'verified'
  'first_name' 
  'last_name' 
  'gender' 
  'locale' 
  'timezone' 
  'updated_time'


как получить email? помогите, пожалуйста
