### ISSUE TITLE
Просьба добавить возможность получения email пользователя из: FaceBook, ВКонтакте, Одноклассники, Mail.ru. 

### ISSUE THREAD

**Issue by AutoWebOffice** [Nodge/yii-eauth#71]
Здравствуйте, 

Огромная просьба добавить возможность получения не только id пользователя, но и email из сервисов:

FaceBook, 
ВКонтакте, 
Одноклассники, 
Mail.ru. 

Очень нужно! 

Вот примеры кодов как это можно сделать:

FaceBook: http://ruseller.com/lessons.php?rub=37&id=1670
ВКонтакте: http://ruseller.com/lessons.php?rub=37&id=1659
Одноклассники: http://ruseller.com/lessons.php?rub=37&id=1661
Mail.ru: http://ruseller.com/lessons.php?rub=37&id=1663

P.S.: Огромное вам спасибо за ваше расширение!

**Comment by alexglue** [comment]
@Nodge "Получить email от Вконтакте и Одноклассников на данный момент возможностей нет."

Не совсем верно на самом деле. Одноклассники email возвращают, но для этого нужно указать scope GET_EMAIL и написать запрос на api-support@ok.ru. 

@AutoWebOffice Тема раскрыта тут: https://toster.ru/q/223988

**Comment by AutoWebOffice** [comment]
Получать в каких ситуациях? Где и для чего?

25 ноября 2015 г., 18:41 пользователь Glue <notifications@github.com>
написал:

> @Nodge <https://github.com/Nodge> "Получить email от Вконтакте и
> Одноклассников на данный момент возможностей нет."
>
> Не совсем верно на самом деле. Одноклассники email возвращают, но для
> этого нужно указать scope GET_EMAIL и написать запрос на api-support@ok.ru.
>
>
> @AutoWebOffice <https://github.com/AutoWebOffice> Тема раскрыта тут:
> https://toster.ru/q/223988
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Nodge/yii-eauth/issues/71#issuecomment-159666489>.
>



-- 

[image: Администрация сервиса АвтоВебОфис]

С уважением, служба заботы о клиентах сервиса АвтоВебОфис
<http://autoweboffice.com/>
zakaz@autoweboffice.com
http://autoweboffice.com
*Важно:*
Полученное Вами сообщение предназначается исключительно для тех лиц,
которым оно адресовано, и может содержать конфиденциальную информацию, либо
информацию, подлежащую разглашению строго определенному кругу лиц.
Изучение, распространение, рассылка, раскрытие кому-либо и прочие способы
использования информации, содержащейся в настоящем сообщении, строго
запрещены. Если Вы получили это сообщение ошибочно, пожалуйста,
незамедлительно сообщите отправителю об этом и удалите со всем содержимым
само сообщение и любые возможные его копии и приложения.

Рекомендуйте АвтоВебОфис и зарабатывайте вместе с нами:
https://autoweboffice.com/partnerskaya-programma

**Comment by msgagaev** [comment]
https://github.com/Nodge/yii-eauth/commit/b3f6390e4e3ce853914db65fc0aed1837714d921
Проблему получения email facebook, к сожалению, не решает.
Получить можно все кроме email.

email сейчас у фейсбука должен отдаваться без проблем
Выдержка из настроек приложения: "email
Provides access to the person's primary email address. This permission is approved by default."

**Comment by Shekhovtsovy** [comment]
Через Вконтакте Email также возвращается если указать SCOPE = 'email'. И забирать его нужно не из пользователя ($this->makeSignedRequest()), а через токен ($this->getAccessTokenData())
